### ISSUE TITLE
CancelTradeFlow - Needs to be implemented [Easy]

### ISSUE THREAD

**Issue by rogersanick** [rogersanick/SettlersOfCordan#14]
Right now players can issue trade states which may be executed by other users to swap tokens. They cannot, however, cancel trades once they are issued. Players should be able to cancel trades at any time.

This ticket depends on: N/A

// States
- No changes required

// Contracts
- Update the TradePhaseContract CancelTrade command with the appropriate business logic #7 

// Flows
- Build a CancelTradeFlow

**Comment by 7khedge** [comment]
Aditya-> I will work on this issue, happy to work with someone else

**Comment by rogersanick** [comment]
Thanks! Please let me know if you have any questions on Corda public slack.
